
2021-04-06 22:29:48,448 - root - readConfig.py - [lineNo: 29] - get_values - INFO - 请确认mysql中的ip是否存在
2021-04-06 22:30:53,455 - root - readConfig.py - [lineNo: 29] - get_values - INFO - 获取options异常,异常原因No section: 'mysql'
2021-04-06 22:59:13,890 - selenium.webdriver.remote.remote_connection - remote_connection.py - [lineNo: 388] - _request - DEBUG - POST 127.0.0.1/wd/hub:4723/session {"capabilities": {"firstMatch": [{"appium:deviceName": "MQS7N19403034263", "platformName": "Android", "appium:platformVersion": "10", "appium:appPackage": "com.ss.android.article.news", "appium:appActivity": "com.ss.android.article.news.activity.MainActivity", "appium:noReset": "true", "appium:unicodeKeyboard": true, "appium:resetKeyboard": true}]}, "desiredCapabilities": {"deviceName": "MQS7N19403034263", "platformName": "Android", "platformVersion": "10", "appPackage": "com.ss.android.article.news", "appActivity": "com.ss.android.article.news.activity.MainActivity", "noReset": "true", "unicodeKeyboard": true, "resetKeyboard": true}}
2021-04-06 22:59:13,892 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (1): 127.0.0.1:80
2021-04-06 22:59:15,949 - urllib3.util.retry - retry.py - [lineNo: 576] - increment - DEBUG - Incremented Retry for (url='/wd/hub:4723/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2021-04-06 22:59:15,949 - urllib3.connectionpool - connectionpool.py - [lineNo: 780] - urlopen - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EBC7D22910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub:4723/session
2021-04-06 22:59:15,950 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (2): 127.0.0.1:80
2021-04-06 22:59:17,968 - urllib3.util.retry - retry.py - [lineNo: 576] - increment - DEBUG - Incremented Retry for (url='/wd/hub:4723/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-04-06 22:59:17,968 - urllib3.connectionpool - connectionpool.py - [lineNo: 780] - urlopen - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EBC7D22D30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub:4723/session
2021-04-06 22:59:17,968 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (3): 127.0.0.1:80
2021-04-06 22:59:19,998 - urllib3.util.retry - retry.py - [lineNo: 576] - increment - DEBUG - Incremented Retry for (url='/wd/hub:4723/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2021-04-06 22:59:19,998 - urllib3.connectionpool - connectionpool.py - [lineNo: 780] - urlopen - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EBC7D22EE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub:4723/session
2021-04-06 22:59:19,998 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (4): 127.0.0.1:80
2021-04-06 23:01:05,689 - root - driver.py - [lineNo: 41] - app_driver - INFO - {'deviceName': 'MQS7N19403034263', 'platformName': 'Android', 'platformVersion': '10', 'appPackage': 'com.ss.android.article.news', 'appActivity': 'com.ss.android.article.news.activity.MainActivity', 'noReset': 'true', 'unicodeKeyboard': True, 'resetKeyboard': True}
2021-04-06 23:01:05,690 - selenium.webdriver.remote.remote_connection - remote_connection.py - [lineNo: 388] - _request - DEBUG - POST 127.0.0.1/wd/hub:4723/session {"capabilities": {"firstMatch": [{"appium:deviceName": "MQS7N19403034263", "platformName": "Android", "appium:platformVersion": "10", "appium:appPackage": "com.ss.android.article.news", "appium:appActivity": "com.ss.android.article.news.activity.MainActivity", "appium:noReset": "true", "appium:unicodeKeyboard": true, "appium:resetKeyboard": true}]}, "desiredCapabilities": {"deviceName": "MQS7N19403034263", "platformName": "Android", "platformVersion": "10", "appPackage": "com.ss.android.article.news", "appActivity": "com.ss.android.article.news.activity.MainActivity", "noReset": "true", "unicodeKeyboard": true, "resetKeyboard": true}}
2021-04-06 23:01:05,690 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (1): 127.0.0.1:80
2021-04-06 23:01:07,716 - urllib3.util.retry - retry.py - [lineNo: 576] - increment - DEBUG - Incremented Retry for (url='/wd/hub:4723/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2021-04-06 23:01:07,717 - urllib3.connectionpool - connectionpool.py - [lineNo: 780] - urlopen - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000160ABD5A910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub:4723/session
2021-04-06 23:01:07,718 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (2): 127.0.0.1:80
2021-04-06 23:01:09,761 - urllib3.util.retry - retry.py - [lineNo: 576] - increment - DEBUG - Incremented Retry for (url='/wd/hub:4723/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2021-04-06 23:01:09,762 - urllib3.connectionpool - connectionpool.py - [lineNo: 780] - urlopen - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000160ABD5AD30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub:4723/session
2021-04-06 23:01:09,762 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (3): 127.0.0.1:80
2021-04-06 23:01:11,798 - urllib3.util.retry - retry.py - [lineNo: 576] - increment - DEBUG - Incremented Retry for (url='/wd/hub:4723/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2021-04-06 23:01:11,799 - urllib3.connectionpool - connectionpool.py - [lineNo: 780] - urlopen - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000160ABD5AEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub:4723/session
2021-04-06 23:01:11,799 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (4): 127.0.0.1:80
2021-04-06 23:03:21,414 - root - driver.py - [lineNo: 41] - app_driver - INFO - {'deviceName': 'MQS7N19403034263', 'platformName': 'Android', 'platformVersion': '10', 'appPackage': 'com.ss.android.article.news', 'appActivity': 'com.ss.android.article.news.activity.MainActivity', 'noReset': 'true', 'unicodeKeyboard': True, 'resetKeyboard': True}
2021-04-06 23:03:21,436 - selenium.webdriver.remote.remote_connection - remote_connection.py - [lineNo: 388] - _request - DEBUG - POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{"appium:deviceName": "MQS7N19403034263", "platformName": "Android", "appium:platformVersion": "10", "appium:appPackage": "com.ss.android.article.news", "appium:appActivity": "com.ss.android.article.news.activity.MainActivity", "appium:noReset": "true", "appium:unicodeKeyboard": true, "appium:resetKeyboard": true}]}, "desiredCapabilities": {"deviceName": "MQS7N19403034263", "platformName": "Android", "platformVersion": "10", "appPackage": "com.ss.android.article.news", "appActivity": "com.ss.android.article.news.activity.MainActivity", "noReset": "true", "unicodeKeyboard": true, "resetKeyboard": true}}
2021-04-06 23:03:21,437 - urllib3.connectionpool - connectionpool.py - [lineNo: 227] - _new_conn - DEBUG - Starting new HTTP connection (1): 127.0.0.1:4723
2021-04-06 23:03:25,130 - urllib3.connectionpool - connectionpool.py - [lineNo: 452] - _make_request - DEBUG - http://127.0.0.1:4723 "POST /wd/hub/session HTTP/1.1" 200 899
2021-04-06 23:03:25,131 - selenium.webdriver.remote.remote_connection - remote_connection.py - [lineNo: 440] - _request - DEBUG - Finished Request
2021-04-06 23:03:31,133 - root - driver.py - [lineNo: 44] - app_driver - INFO - ----APP已经启动------
